# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "github.com/hashicorp/consul"
  version = "1.2.2"

[prune]
  go-tests = true
  unused-packages = true

       execexec - execute command in current process
        -

   [1mSynopsis[0m
       [1mexec[0m COMMAND [OPTIONS...]

   [1mDescription[0m
       exec replaces the currently running shell with a new command. On
       successful completion, exec never returns. exec cannot be used inside a
       pipeline.

   [1mExample[0m
       exec emacs starts up the emacs text editor, and exits fish. When emacs
       exits, the session will terminate.

